name: flutter_piano
description: A Crossplatform Midi Piano built with Flutter.
author: Rody Davis Jr <rody.davis.jr@gmail.com>
homepage: https://github.com/AppleEducate/flutter_piano
version: 1.0.2+30

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tonic: ^0.2.3
  cupertino_icons: ^0.1.2
  vibrate: ^0.0.4
  localstorage: ^2.0.0
  flutter_midi: ^1.0.0
  app_review: ^1.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.15.7
  font_awesome_flutter: ^8.4.0
  persist_theme: ^1.0.3
  webview_flutter: ^0.3.7
  flutter_webview_plugin: ^0.3.5
  http: ^0.12.0
  encrypt: ^3.1.0
  auto_orientation: ^1.0.1
  scoped_model: ^1.0.1
  orientation: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.5.1
  screenshots: ^0.1.7
  intl_translation: ^0.17.2

dependency_overrides:
  localstorage:
    git: https://github.com/AppleEducate/flutter_localstorage

flutter:
  uses-material-design: true

  assets:
   - assets/sounds/Piano.sf2
